name = "neetbox"

[logging]

[pipeline]
updateInterval = 10

[daemon]
enable = true
server = "localhost"
port = 20202
allowIpython = false
mute = true
mode = "attached"
uploadInterval = 10

[integrations.environment.hardware]
monit = "true"

[integrations.environment.platform]
monit = "true"
