name = "neetbox"
workspace-id = "b42c4749-1fa8-4a9d-ae30-80e2c69309f8"

[logging]
level = "INFO"

[pipeline]
updateInterval = 0.5

[extension]
autoload = false

[daemon]
enable = true
host = "127.0.0.1"
port = 20202
allowIpython = false
mute = true
mode = "detached"
uploadInterval = 0.5

[extension.environment.hardware]
monit = true
interval = 0.5

[extension.environment.platform]
monit = true
