name = "neetbox"
version = "0.4.4"
projectId = "3edbc5ed-8e16-44fe-8c25-949a8cb833e6"

[logging]
level = "INFO"
logdir = "logs"

[extension]
autoload = true

[client]
enable = true
host = "127.0.0.1"
port = 20202
allowIpython = false
mute = true
mode = "detached"
uploadInterval = 1

[client.shell]
enable = true
daemon = true

[extension.machine.hardware]
interval = 2
