name = "neetbox"
version = "0.3.5"
projectId = "d3aacc9f-ff40-400d-9a4d-f5f9cea8e343"

[logging]
level = "INFO"
logdir = "logs"

[extension]
autoload = true

[client]
enable = true
host = "127.0.0.1"
port = 5000
allowIpython = false
mute = true
mode = "detached"
uploadInterval = 1

[client.shell]
enable = true
daemon = true

[extension.environment.hardware]
interval = 2
