name = "neetbox"
version = "0.3.3"
projectid = "e1b97d6a-089c-433a-a8a5-95be751932fc"

[logging]
level = "INFO"
logdir = "logs"

[extension]
autoload = true

[client]
enable = true
host = "127.0.0.1"
port = 20202
allowIpython = false
mute = true
mode = "detached"
uploadInterval = 1

[extension.environment.hardware]
interval = 2
