name = "neetbox"

[logging]

[pipeline]
updateInterval = 10

[integrations]
datasets = []

[daemon]
enable = true
allowIpython = false
mute = true

[integrations.environment]
gpus = "auto"

[daemon.server]
mode = "detached"
port = 20202

[daemon.client]
server = "localhost"
port = 20202
uploadInterval = 10
