name = "neetbox"

[logging]
level = "INFO"

[pipeline]
updateInterval = 0.5

[integrations]
autoload = false

[daemon]
enable = true
host = "localhost"
port = 20202
allowIpython = false
mute = true
mode = "detached"
uploadInterval = 0.5

[integrations.environment.hardware]
monit = true
interval = 0.5

[integrations.environment.platform]
monit = true
