[tool.poetry]
name = "neetbox"
version = "0.1.516"
description = "NEETBox contains useless CV code snippets."
license = "MIT"
authors = ["VisualDust <gavin@gong.host>"]
maintainers = [
    "VisualDust <gavin@gong.host>",
    "PommesPeter <me@pommespeter.space>",
    "PaperCube <imzhy@hotmail.com>",
    "PuQing <me@puqing.work>",
    "Lideming <me@yuuza.net>"
]


readme = "README.md"
homepage = "https://neetbox.550w.host"
repository = "https://github.com/visualDust/neetbox"
keywords = ["computer vision", "tools", "logging"]
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Framework :: Matplotlib",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Visualization",
    "Topic :: Software Development :: Testing",
    "Topic :: System :: Logging",
    "Topic :: Utilities",
]

# [[tool.poetry.source]]
# name = "pypi"
# url = "https://pypi.org/simple"
# default = true

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
toml = ">0.10"
injector = ">=0.20"
setproctitle = ">=1.0"
rich = ">=13"
numpy = "^1.26.0"
pillow = "^10.0.1"
pre-commit = ">=3.4.0"
click = "^8.1.7"
pytest = "^7.4.3"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
httpx = "^0.24.0"
flask = "^2.2.3"
black = "^23.9.1"
isort = "^5.11.5"

[tool.poetry.extras]
torch = ["torch", "torchvision", "torchaudio"]

transformer = ["transformers"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry.scripts]
neet = 'neetbox.cli.parse:main'
