name: Frontend Build & Lint

on:
  push:
    paths:
      - 'neetbox/frontend/**'
  pull_request:
    paths:
      - 'neetbox/frontend/**'


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: neetbox/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'
          cache-dependency-path: 'neetbox/frontend/yarn.lock'
      - name: setup yarn
        run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn tsc
        if: '!cancelled()'
      - run: yarn lint
        if: '!cancelled()'
      - run: yarn prettier-check
        if: '!cancelled()'
