name: Frontend Build & Lint

on: ["pull_request", "push"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: neetbox/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: setup yarn
        run: corepack enable
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn tsc
        if: '!cancelled()'
      - run: yarn lint
        if: '!cancelled()'
