# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Manually Build Python Package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "neetbox/frontend/yarn.lock"
      - name: setup yarn
        run: corepack enable
        working-directory: neetbox/frontend
      - run: yarn install --frozen-lockfile
        working-directory: neetbox/frontend
      - run: yarn build
        working-directory: neetbox/frontend
      - name: Build and publish to pypi
        run: ls ${{github.workspace}}/neetbox/frontend_dist
