name: Run pytest
on: ["pull_request","push"]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install
      uses: abatilo/actions-poetry@v2
      with:
        python_version: 3.8
        poetry_version: 1.0
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@v2
      with:
        python_version: 3.8
        poetry_version: 1.0
        args: poetry run pytest
